workflows:
  tfaraj-android:
    name: TFARAJ Android
    max_build_duration: 60

    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.tfaraj.app"
      groups:
        - firebase

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Analyze Flutter project
        script: |
          flutter analyze

      - name: Build APK
        script: |
          flutter build apk --release

      - name: Build AAB
        script: |
          flutter build appbundle --release

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab
