import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android: return android;
      case TargetPlatform.iOS: return ios;
      case TargetPlatform.macOS: return macos;
      default: throw UnsupportedError('Firebase is not configured for this platform.');
    }
  }

  // Web values are copied from the original TFARAJ PWA Firebase configuration.
  static const web = FirebaseOptions(
    apiKey: 'AIzaSyCEvcOasOQrXu8AFxQzkCRT4WWXpcQNkLg',
    appId: '1:204225804392:web:56995d6c7b69e3cbd5e3dd',
    messagingSenderId: '204225804392',
    projectId: 'tfaraj-app',
    authDomain: 'tfaraj-app.firebaseapp.com',
    storageBucket: 'tfaraj-app.firebasestorage.app',
    measurementId: 'G-QBL660MVBL',
  );

  // Replace these with values generated by `flutterfire configure` for the Android app.
  static const android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_ANDROID_API_KEY',
    appId: 'REPLACE_WITH_ANDROID_APP_ID',
    messagingSenderId: '204225804392',
    projectId: 'tfaraj-app',
    storageBucket: 'tfaraj-app.firebasestorage.app',
  );

  static const ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_IOS_API_KEY',
    appId: 'REPLACE_WITH_IOS_APP_ID',
    messagingSenderId: '204225804392',
    projectId: 'tfaraj-app',
    storageBucket: 'tfaraj-app.firebasestorage.app',
    iosBundleId: 'com.tfaraj.app',
  );

  static const macos = ios;
}
